version: '3.8'

services:
  backend:
    build:
      context: .
      target: production
    environment:
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      - database
      - redis
    networks:
      - app-network
    

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: E62ffcc5Bc3fCaDB4feB4bEG2CG31bge
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  database-data:
  redis-data:
