version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: 84KF2Oxo3J
       POSTGRES_DB: main
    networks:
      - zephChambers
  db:
  volumes:
    - dbdata:/var/lib/postgresql/data
  cache:
    volumes: 
     - cachedata:/data
networks:
  zephChambers:

#   volumes:
#   dbdata:
#   cachedata:

# services:



